- Glances:
    - Info:
        widget:
          type: glances
          url: http://host.containers.internal:61208
          metric: info
          chart: false
    - CPU Temp:
        widget:
          type: glances
          url: http://host.containers.internal:61208
          metric: sensor:Package id 0
          chart: false
    - Processes:
        widget:
          type: glances
          url: http://host.containers.internal:61208
          metric: process
          chart: false
    - Network:
        widget:
          type: glances
          url: http://host.containers.internal:61208
          metric: network:enp1s0
          chart: false

- Arr: []

- Downloads: []

- Media: []

- Services: []
